# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Muhammad Rizwan
title: PhD Computer Science
email: rizwan2phd@gmail.com
# email_title: Email (Email title override)
phone: 0092 321 6715644
# phone_title: Phone (Phone title override)
website: 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: rizwan2phd
github_username:  rizwan2phd
stackoverflow_username: 
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: muhammad-rizwan-phd-a884659a
xing_username: 
pinterest_username: 
youtube_username: 
orcid_username: 0000-0001-6286-2544
googlescholar_username: rizwan2phd

# Additional icon links

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Full Time Lecturer, Information Technology
        sub_title: Khwaja Fareed University of Engineering and Information Technology, Pakistan
        caption: February 2016 - present
        link: https://kfueit.edu.pk/
        quote: >
          Responsibilities:
        description: | # this will include new lines to allow paragraphs
          Delivering lectures on subjects such as Object-Oriented Programming, Enterprise Systems, Data Science, and Mobile Application Programming, involves preparing comprehensive course materials including syllabi, assignments, and assessments to ensure effective learning outcomes for students. Responsibilities also include serving as a Batch Advisor, offering guidance on study plans and course enrollment, and mentoring final-year projects for computer science and information technology students. Actively participating in curriculum development through Board of Studies meetings, conducting fair evaluations of student performance via quizzes, exams, projects, and presentations, and facilitating industry-academia interactions by organizing guest lectures, workshops, and seminars with industry professionals are also key duties. Additionally, conducting research and publishing findings in reputable journals to advance knowledge in the field is a critical component of the role.

      - layout: left
        title: Visiting Lecturer, Computer Science
        sub_title: The Islamia University of Bahawalpur, Pakistan
        caption: 2013 - 2015
        link: https://www.iub.edu.pk/
        quote: >
          Responsibilities:
        description: | # this will include new lines to allow paragraphs
          Delivering lectures to computer science undergraduates involves preparing comprehensive course materials, including syllabi, assignments, and assessments, to ensure effective learning outcomes. This role also includes conducting fair and timely evaluations of student performance through quizzes, exams, projects, and presentations.
  - title: Education
    layout: list
    content:
      - layout: left
        title: PhD (Computer Science)
        sub_title: The Islamia University of Bahawalpur, Pakistan
        caption: 2016 - 2023
        quote: >
          Thesis Title: Early Depression Prediction Based On Social Media Data Using Machine Learning Techniques
        description: | # this will include new lines to allow paragraphs
          The PhD thesis explores methods to classify depression expressed in social media posts, focusing on intensity rather than binary classification. It addresses the challenge of noise in social media data and proposes techniques using machine learning and deep learning models. After annotating tweets into three depression classes, FastText models and an ensemble approach are applied, achieving an 84% f1 score and 90% accuracy, outperforming baselines. The study evaluates transformer-based models, highlighting Electra Small Generator (ESG) as the best performer due to its deep contextualized text representation with an 89\% F1 score, even surpassing larger models like DistilBert. Additionally, optimization of ESG through post-training quantization is suggested for deployability to embedded devices without compromising performance, demonstrating its closeness in performance to the proposed ensemble approach. The research aids in better depression intensity classification on Twitter and helps in selecting optimal language models for similar NLP tasks with less training time.
     
      - layout: left
        title: MS (Computer Science)
        sub_title: The Islamia University of Bahawalpur, Pakistan
        caption: 2013 - 2015
        quote: >
          Thesis Title: Opinion Mining in Geo-Tagged Tweets of Political Domain of Pakistan
        description: | # this will include new lines to allow paragraphs
          The Master thesis focuses on analyzing Twitter data to gauge the temporal popularity of top political parties in Pakistan, aiming to provide an alternative to potentially biased traditional survey methods. By collecting 1.3 million geo-tagged tweets and employing sentiment analysis techniques including lexicon-based and machine learning algorithms, it assesses sentiment accuracy and favors SentiStrength for its quantitative sentiment measurement. Biased data is filtered, and sentiment scores are averaged over time to evaluate party popularity across different geographical areas. Additionally, the thesis outlines rules to identify influential events using hashtags that impact party popularity chronologically. An prototype application is also developed to display political popularity trends through statistical graphs for each party, alongside sentiment visualizations on maps based on tweet locations.

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <mark>First Author</mark> **"Prevalent Frequency of Emotional and Physical Symptoms in Social Anxiety using Zero Shot Classification: An Observational Study."** Proceedings of the 9th Workshop on Computational Linguistics and Clinical Psychology (CLPsych 2024). <mark>2024</mark>.
      - <mark>First Author</mark> "Depression Intensity Classification from Tweets Using FastText Based Weighted Soft Voting Ensemble." Computers, Materials & Continua 78.2 (<mark>2024</mark>): 2047-2066.
      - <mark>Corresponding Author</mark> "Unifying Sentence Transformer Embedding and Softmax Voting Ensemble for Accurate News Category Prediction." Computers 12.7 (<mark>2023</mark>): 137.
      - <mark>First Author</mark> "Depression classification from tweets using small deep transfer learning language models." IEEE Access 10 (<mark>2022</mark>): 129176-129189.
      - <mark>Co-Author</mark> "Dual Language Sentiment Analysis Model for YouTube Videos Ranking Based on Machine Learning Techniques." Pakistan Journal of Engineering and Technology 3.2 (<mark>2020</mark>): 213-218.
      - <mark>Co-Author</mark> "Sentiment base emotions classification of celebrity tweets by using R language." Pakistan Journal of Engineering and Technology 3.2 (<mark>2020</mark>): 95-99.
      - <mark>Co-Author</mark> "Multi-Class Classification of the YouTube Comments using Machine Learning." Pakistan Journal of Engineering and Technology 3.2 (<mark>2020</mark>): 183-188.
      - <mark>Co-Author</mark> "Recommendation of effectiveness of YouTube video contents by qualitative sentiment analysis of its comments and replies." Pakistan Journal of Science 71.4 (<mark>2019</mark>): 91.
    
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
